version: "3"
services: 
    app:
        env_file:
            - prod.env
        container_name: "card-game"
        restart: "always"
        build: .
        ports: 
            - "3000:3000"
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"